### PR TITLE
Adds Cosmic helper scripts

### PR DESCRIPTION
**Pull request by wilderrodrigues**
- Copies the ACS ones replacing claudstack by cosmic[-core]

I tested the following scripts:

* ./build_run.sh 
* ./package44_wrapper.sh 
* ./run_marvin_router_tests.sh 

Concerning the check-pr scripts, we have to discuss about the ```git fetch origin pull/${prId}/head:pr/${prId}``` command with the submodules.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @miguelaferreira @borisroman @remibergsma @bheuvel

**Comment by remibergsma** [comment]
For me, `build_run_deploy_test.sh` is the most important script. Please hold merging, we should first move MCT-shared from SBP to this repo so we won't lose the issues, PRs and other linked things. I can look into that tomorrow.

**Comment by wilderrodrigues** [comment]
Remi, those files are in a new directory. The original files, used by you for testing purposes, remained untouched.

Those new files are needed for those running tests with the new code base.

Cheers,
Wilder

Sent from my iPhone

On 25 Jan 2016, at 17:42, Remi Bergsma <notifications@github.com<mailto:notifications@github.com>> wrote:


For me, build_run_deploy_test.sh is the most important script. Please hold merging, we should first move MCT-shared from SBP to this repo so we won't lose the issues, PRs and other linked things. I can look into that tomorrow.

**Comment by remibergsma** [comment]
@wilderrodrigues True. The thing is that I made a new repo and that wasn't the smartest thing. So I want to move the other one, rename it to 'cosmic-bubble' and then merge this PR. We'll discuss tomorrow.

**Comment by wilderrodrigues** [comment]
Is the cosmic-bubble the most recent one? If so, we just delete the old one.

Indeed it should have been moved to the new org then renamed, not just copied/pasted.

We now do either way, doesn't really matter. :)

Sent from my iPhone

On 25 Jan 2016, at 17:56, Remi Bergsma <notifications@github.com<mailto:notifications@github.com>> wrote:


@wilderrodrigues<https://github.com/wilderrodrigues> True. The thing is that I made a new repo and that wasn't the smartest thing. So I want to move the other one, rename it to 'cosmic-bubble' and then merge this PR. We'll discuss tomorrow.

**Comment by remibergsma** [comment]
No, the MCT one is newer. Friday I ported the changes in cosmic-bubble back to MCT. Moving that one and renaming it keeps the existing forks. We'll fix it tomorrow :-)

**Comment by wilderrodrigues** [comment]
will reopen this PR against MCCT. 

@remibergsma, can I delete this Repo and proceed with moving the the other repo to the MCC organisation and renaming it?

**Pull request closed without merging**
